#!/usr/bin/env bash
# Cedar boots under Secure Boot only if its signed EFI payload and kernel are
# byte-identical to the base's. Compares content digests, not package metadata.
#
# Exit 0 = payload matches. Exit 1 = Cedar broke it. Exit 2 = the guard itself
# is broken — bad/missing image argument, no usable base image, or an empty
# or partial manifest. A misconfiguration is never a Secure Boot regression,
# so it must never be reported as exit 1.
set -euo pipefail

usage() { echo "usage: boot-chain.sh <image>" >&2; exit 2; }
if [ $# -lt 1 ] || [ -z "$1" ]; then usage; fi
IMAGE="$1"

PLATFORM="${PLATFORM:-linux/amd64}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Default to the base image this repo actually builds from, read straight out
# of the Containerfile, so `just test`/`just check` work with no environment
# set up and can never silently compare Cedar against a base the build didn't
# use. An explicit CEDAR_BASE still overrides this.
default_base() {
  awk '/^FROM /{print $2; exit}' "$SCRIPT_DIR/../Containerfile" 2>/dev/null || true
}
BASE="${CEDAR_BASE:-$(default_base)}"
if [ -z "$BASE" ]; then
  echo "FAIL: CEDAR_BASE is unset and no FROM line could be read from" \
       "$SCRIPT_DIR/../Containerfile" >&2
  exit 2
fi

# Observed against localhost/cedar:dev and its base in Task 5: 16 files (13
# under /usr/lib/efi, 2 bootupd manifests, vmlinuz) — one fewer than Task 4's
# 17 since initramfs.img is no longer hashed (see manifest() below). This is
# a coarse backstop; the per-subtree checks inside manifest() below are what
# actually catch a subtree (e.g. grub2) going missing without shrinking the
# total enough to trip a single floor.
MIN_FILES=16

count_lines() { wc -l < "$1" | tr -d '[:space:]'; }

WORK=$(mktemp -d); trap 'rm -rf "$WORK"' EXIT

# Paths verified against the real image in Task 1. Do NOT substitute the
# "obvious" ones: /usr/lib/ostree-boot/efi is EMPTY in this image, and
# /usr/lib/bootupd/updates/{EFI,BIOS}.json are metadata, not binaries. The
# signed payload lives under /usr/lib/efi/{grub2,shim}/<rpm-evr>/EFI/, where
# the <rpm-evr> segment drifts with package updates — which is why this walks
# the whole /usr/lib/efi tree rather than globbing a version into a path.
#
# /usr/lib/bootupd/updates/*.json IS hashed: it is bootupd's manifest and
# records the payload versions (grub2-1:2.12-64.fc44,shim-16.1-5), so a
# version change trips the guard even if a binary somehow hashed the same.
#
# /usr/lib/bootupd/grub2-static/ is deliberately NOT hashed: those are GRUB
# config fragments, not signed binaries, and Cedar may legitimately edit them.
manifest() {
  podman run --rm --platform="$PLATFORM" --entrypoint "" "$1" sh -c '
    set -e
    for d in /usr/lib/efi/grub2 /usr/lib/efi/shim; do
      [ -d "$d" ] && [ -n "$(find "$d" -type f -o -type l)" ] || { echo "missing/empty: $d" >&2; exit 1; }
    done
    find /usr/lib/efi \( -type f -o -type l \) -exec sha256sum {} +
    sha256sum /usr/lib/bootupd/updates/*.json
    for k in /usr/lib/modules/*/; do
      # initramfs.img is deliberately regenerated by Cedar (Plymouth theme) and
      # is not a signed EFI binary. vmlinuz stays guarded.
      sha256sum "$k"vmlinuz
    done
  ' | sort -k2
}

for side in base cedar; do
  img=$([ "$side" = base ] && echo "$BASE" || echo "$IMAGE")
  if ! manifest "$img" > "$WORK/$side" 2>"$WORK/$side.err"; then
    echo "FAIL: could not build manifest for $img" >&2
    sed 's/^/       /' "$WORK/$side.err" >&2
    exit 2
  fi
  n=$(count_lines "$WORK/$side")
  if (( n < MIN_FILES )); then
    echo "FAIL: $img yielded only $n boot files (expected >= $MIN_FILES)" >&2
    echo "      the guard is broken, not the image" >&2
    exit 2
  fi
done

echo "Boot chain guard"
if diff -u "$WORK/base" "$WORK/cedar"; then
  echo "  ok   signed boot payload byte-identical to base ($(count_lines "$WORK/cedar") files)"
else
  echo "  FAIL Cedar's signed boot payload differs from the base"
  exit 1
fi
